// Console is the lab's control panel: one page that shows which simulated
// services are up, what the sim banks hold, and lets you create the
// merchants the money flow needs before any of it means anything.
//
// It is a client of the other services and nothing more. Every button here
// makes the same HTTP call a human with curl would make, against the same
// public surface, so nothing in this lab can only be reached through a UI.
// The console being down must never be why a scenario cannot run.
package main

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"embed"
	"io/fs"
	"log"
	"net/http"
	"os"
	"strconv"
	"time"

	"github.com/webduvet/fintechlab-simple/internal/console"
	"github.com/webduvet/fintechlab-simple/internal/httputilx"
)

//go:embed web
var webFS embed.FS

type app struct {
	cat     *console.Catalogue
	mon     *console.Monitor
	reg     *console.Registry
	banks   *console.Banks
	prov    *console.Provisioner
	client  *http.Client
	secure  *http.Client
	bcCfg   string
	provErr string
	// bc is the same Banking Circle client the Banks view uses, kept
	// directly so the Configuration view can ask the service what delivery
	// schedule it is *actually* running.
	bc *console.BankingCircleBank
}

func main() {
	addr := env("LISTEN", ":8090")

	plain := &http.Client{Timeout: 10 * time.Second}
	secure, tlsErr := tlsClient(
		env("CA_FILE", "certs/ca.pem"),
		env("CLIENT_CERT", "certs/client.pem"),
		env("CLIENT_KEY", "certs/client-key.pem"),
	)
	if tlsErr != nil {
		// Not fatal. Without the CA the Banking Circle panels report why
		// they are empty, and the rest of the console still works --
		// a control panel that refuses to start because one peer's
		// credentials are missing is worse than one that says so.
		log.Printf("console: no TLS client material (%v); banking-circle panels will show the error", tlsErr)
		secure = plain
	}

	cat := console.DefaultCatalogue()
	a := &app{
		cat:    cat,
		client: plain,
		secure: secure,
		bcCfg:  env("CONSOLE_BC_DELIVERY_CONFIG", "config/banking-circle.json"),
	}
	a.mon = console.NewMonitor(cat, a.clientFor, envDuration("CONSOLE_PROBE_INTERVAL", 5*time.Second), 3*time.Second)

	reg, err := console.NewRegistry(env("CONSOLE_STATE_FILE", "console-data/registry.json"))
	if err != nil {
		log.Fatalf("console: registry: %v", err)
	}
	a.reg = reg

	a.bc = &console.BankingCircleBank{
		BaseURL:  a.baseURL("banking-circle"),
		Client:   secure,
		User:     env("BC_USER", "sim"),
		Password: env("BC_PASSWORD", "sim-bc-dev-only"),
	}
	a.banks = console.NewBanks(
		&console.CoreLedgerBank{BaseURL: a.baseURL("bank"), Client: plain},
		a.bc,
	)

	prov, err := console.NewProvisioner(plain, reg,
		a.baseURL("b4b"),
		env("B4B_JWT_PRIVATE_KEY_PATH", "b4b-keys/private.pem"),
		env("B4B_JWT_KEY_ID", "b4b-mock-1"),
		a.baseURL("worldline"),
	)
	a.prov = prov
	if err != nil {
		// Same reasoning as the TLS material: the key is generated by the
		// b4b service into a shared volume, so a console started first
		// simply has not seen it yet.
		a.provErr = err.Error()
		log.Printf("console: %v (payout-rail provisioning disabled until the key is readable)", err)
	}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	go a.mon.Run(ctx)

	log.Printf("console listening on %s", addr)
	log.Fatal(http.ListenAndServe(addr, logReq(a.routes())))
}

func (a *app) routes() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /health", func(w http.ResponseWriter, r *http.Request) {
		httputilx.WriteJSON(w, 200, map[string]string{"status": "ok", "service": "console"})
	})

	mux.HandleFunc("GET /api/flow", a.flow)
	mux.HandleFunc("GET /api/overview", a.overview)
	mux.HandleFunc("POST /api/services/{id}/probe", a.probeService)
	mux.HandleFunc("GET /api/services/{id}/activity", a.serviceActivity)

	mux.HandleFunc("GET /api/banks", a.listBanks)
	mux.HandleFunc("POST /api/banks/{id}/accounts", a.openAccount)

	mux.HandleFunc("GET /api/merchants", a.listMerchants)
	mux.HandleFunc("POST /api/merchants", a.createMerchant)
	mux.HandleFunc("DELETE /api/merchants/{id}", a.deleteMerchant)
	mux.HandleFunc("POST /api/merchants/{id}/outlets", a.addOutlet)
	mux.HandleFunc("POST /api/merchants/{id}/status", a.setMerchantStatus)
	mux.HandleFunc("POST /api/merchants/{id}/provision", a.provisionMerchant)
	mux.HandleFunc("POST /api/merchants/{id}/trading", a.seedTrading)
	mux.HandleFunc("POST /api/outlets/{mid}/sanctions", a.setSanctions)
	mux.HandleFunc("POST /api/partners", a.createPartner)

	mux.HandleFunc("GET /api/config", a.getConfig)
	mux.HandleFunc("PUT /api/config/worldline-channel", a.putWorldlineChannel)

	mux.HandleFunc("POST /api/actions/worldline-cycle", a.runWorldlineCycle)
	mux.HandleFunc("POST /api/actions/settlement-pull", a.settlementPull)
	mux.HandleFunc("POST /api/actions/runner-settle", a.runnerSettle)
	mux.HandleFunc("POST /api/actions/runner-fund-sga", a.runnerFundSGA)

	sub, err := fs.Sub(webFS, "web")
	if err != nil {
		log.Fatalf("console: embedded assets: %v", err)
	}
	mux.Handle("GET /", http.FileServer(http.FS(sub)))
	return mux
}

// clientFor picks the HTTP client for a service. Banking Circle's
// real-shaped listener wants a client certificate; nothing else does.
func (a *app) clientFor(s console.Service) *http.Client {
	if len(s.BaseURL) > 5 && s.BaseURL[:5] == "https" {
		return a.secure
	}
	return a.client
}

func (a *app) baseURL(id string) string {
	s, ok := a.cat.Get(id)
	if !ok {
		return ""
	}
	return s.BaseURL
}

// tlsClient trusts caFile and presents the client certificate when both
// halves are present -- Banking Circle's API requires mTLS by default.
func tlsClient(caFile, certFile, keyFile string) (*http.Client, error) {
	pem, err := os.ReadFile(caFile)
	if err != nil {
		return nil, err
	}
	pool := x509.NewCertPool()
	if !pool.AppendCertsFromPEM(pem) {
		return nil, os.ErrInvalid
	}
	cfg := &tls.Config{RootCAs: pool, MinVersion: tls.VersionTLS12}
	if cert, err := tls.LoadX509KeyPair(certFile, keyFile); err == nil {
		cfg.Certificates = []tls.Certificate{cert}
	}
	return &http.Client{
		Timeout:   10 * time.Second,
		Transport: &http.Transport{TLSClientConfig: cfg},
	}, nil
}

func env(k, def string) string {
	if v := os.Getenv(k); v != "" {
		return v
	}
	return def
}

func envDuration(k string, def time.Duration) time.Duration {
	v := os.Getenv(k)
	if v == "" {
		return def
	}
	if d, err := time.ParseDuration(v); err == nil && d > 0 {
		return d
	}
	if n, err := strconv.Atoi(v); err == nil && n > 0 {
		return time.Duration(n) * time.Second
	}
	log.Printf("console: %s=%q is not a duration; using %s", k, v, def)
	return def
}

func logReq(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Static asset noise drowns out the calls that matter.
		if r.URL.Path != "/" && len(r.URL.Path) > 4 && r.URL.Path[:5] == "/api/" {
			log.Printf("%s %s", r.Method, r.URL.Path)
		}
		next.ServeHTTP(w, r)
	})
}
