// Console is the lab's control panel: one page that shows which simulated
// services are up, what the sim banks hold, and lets you create the
// merchants the money flow needs before any of it means anything.
//
// It is a client of the other services and nothing more. Every button here
// makes the same HTTP call a human with curl would make, against the same
// public surface, so nothing in this lab can only be reached through a UI.
// The console being down must never be why a scenario cannot run.
package main

import (
	"context"
	"crypto/sha256"
	"crypto/tls"
	"crypto/x509"
	"embed"
	"encoding/hex"
	"io/fs"
	"log"
	"net/http"
	"os"
	"strconv"
	"time"

	"github.com/webduvet/fintechlab-simple/internal/console"
	"github.com/webduvet/fintechlab-simple/internal/httputilx"
	"github.com/webduvet/fintechlab-simple/internal/waitfor"
)

//go:embed web
var webFS embed.FS

type app struct {
	cat     *console.Catalogue
	mon     *console.Monitor
	reg     *console.Registry
	banks   *console.Banks
	prov    *console.Provisioner
	client  *http.Client
	secure  *http.Client
	bcCfg   string
	provErr string
	// keysDir is the lab's keys directory, read for the connect-your-
	// platform downloads.
	keysDir string
	// bcInternal is Banking Circle's internal bridge, where Worldline's
	// wire into the safeguarding accounts lands (Fund safeguarding
	// accounts on its card).
	bcInternal string
	// bc is the same Banking Circle client the Banks view uses, kept
	// directly so the Configuration view can ask the service what delivery
	// schedule it is *actually* running.
	bc *console.BankingCircleBank
}

func main() {
	addr := env("LISTEN", ":8090")

	plain := &http.Client{Timeout: 10 * time.Second}
	secure, tlsErr := tlsClient(
		env("CA_FILE", "keys/certs/ca.pem"),
		env("CLIENT_CERT", "keys/certs/client.pem"),
		env("CLIENT_KEY", "keys/certs/client-key.pem"),
	)
	if tlsErr != nil {
		// Not fatal. Without the CA the Banking Circle panels report why
		// they are empty, and the rest of the console still works --
		// a control panel that refuses to start because one peer's
		// credentials are missing is worse than one that says so.
		log.Printf("console: no TLS client material (%v); banking-circle panels will show the error", tlsErr)
		secure = plain
	}

	cat := console.DefaultCatalogue()
	a := &app{
		cat:     cat,
		client:  plain,
		secure:  secure,
		bcCfg:   env("CONSOLE_BC_DELIVERY_CONFIG", "config/banking-circle.json"),
		keysDir: env("CONSOLE_KEYS_DIR", "keys"),
		// The bridge, not the credentialed API: crediting a safeguarding
		// account stands in for a wire arriving, and the real bank has no
		// caller-facing route for that.
		bcInternal: env("CONSOLE_BC_INTERNAL_URL", "http://127.0.0.1:8095"),
	}
	a.mon = console.NewMonitor(cat, a.clientFor, envDuration("CONSOLE_PROBE_INTERVAL", 5*time.Second), 3*time.Second)

	reg, err := console.NewRegistry(env("CONSOLE_STATE_FILE", "console-data/registry.json"))
	if err != nil {
		log.Fatalf("console: registry: %v", err)
	}
	a.reg = reg

	a.bc = &console.BankingCircleBank{
		BaseURL:  a.baseURL("banking-circle"),
		Client:   secure,
		User:     env("BC_USER", "sim"),
		Password: env("BC_PASSWORD", "sim-bc-dev-only"),
	}
	a.banks = console.NewBanks(
		&console.CoreLedgerBank{BaseURL: a.baseURL("bank"), Client: plain},
		a.bc,
	)

	// b4b writes its signing key on first start, concurrently with this one
	// on a fresh keys volume, and the provisioner reads it only here. A
	// short wait beats a console that says "disabled" until restarted.
	b4bKey := env("B4B_JWT_PRIVATE_KEY_PATH", "keys/b4b-keys/private.pem")
	_ = waitfor.Files(30*time.Second, b4bKey)
	prov, err := console.NewProvisioner(plain, reg,
		a.baseURL("b4b"),
		b4bKey,
		env("B4B_JWT_KEY_ID", "b4b-mock-1"),
		a.baseURL("worldline"),
	)
	a.prov = prov
	if err != nil {
		// Same reasoning as the TLS material: the key is generated by the
		// b4b service into a shared volume, so a console started first
		// simply has not seen it yet.
		a.provErr = err.Error()
		log.Printf("console: %v (payout-rail provisioning disabled until the key is readable)", err)
	}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	go a.mon.Run(ctx)

	log.Printf("console listening on %s", addr)
	log.Fatal(http.ListenAndServe(addr, logReq(a.routes())))
}

func (a *app) routes() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /health", func(w http.ResponseWriter, r *http.Request) {
		httputilx.WriteJSON(w, 200, map[string]string{"status": "ok", "service": "console"})
	})

	mux.HandleFunc("GET /api/flow", a.flow)
	mux.HandleFunc("GET /api/flow/hops/{id}", a.flowHop)
	mux.HandleFunc("GET /api/stand-ins", a.listStandIns)
	mux.HandleFunc("POST /api/stand-ins/{id}", a.setStandIn)
	mux.HandleFunc("GET /api/overview", a.overview)
	mux.HandleFunc("POST /api/services/{id}/probe", a.probeService)
	mux.HandleFunc("GET /api/services/{id}/activity", a.serviceActivity)
	mux.HandleFunc("GET /api/banking-circle/subscriptions", a.bcSubscriptions)
	mux.HandleFunc("POST /api/banking-circle/subscriptions/{id}/test", a.bcSubscriptionTest)
	mux.HandleFunc("POST /api/banking-circle/subscriptions/{id}/pause", a.bcSubscriptionPause)
	mux.HandleFunc("POST /api/banking-circle/subscriptions/{id}/resume", a.bcSubscriptionPause)
	mux.HandleFunc("GET /api/banking-circle/payouts", a.bcPayouts)
	mux.HandleFunc("POST /api/banking-circle/payouts/{id}/return", a.bcPayoutAction)
	mux.HandleFunc("POST /api/banking-circle/payouts/{id}/reverse", a.bcPayoutAction)

	mux.HandleFunc("GET /api/banks", a.listBanks)
	mux.HandleFunc("POST /api/banks/{id}/accounts", a.openAccount)

	mux.HandleFunc("GET /api/merchants", a.listMerchants)
	mux.HandleFunc("POST /api/merchants", a.createMerchant)
	mux.HandleFunc("DELETE /api/merchants/{id}", a.deleteMerchant)
	mux.HandleFunc("POST /api/merchants/{id}/outlets", a.addOutlet)
	mux.HandleFunc("POST /api/merchants/{id}/status", a.setMerchantStatus)
	mux.HandleFunc("POST /api/merchants/{id}/provision", a.provisionMerchant)
	mux.HandleFunc("POST /api/merchants/{id}/trading", a.seedTrading)
	mux.HandleFunc("POST /api/outlets/{mid}/sanctions", a.setSanctions)
	mux.HandleFunc("POST /api/partners", a.createPartner)

	mux.HandleFunc("GET /api/connect", a.connect)
	mux.HandleFunc("GET /api/connect/env", a.connectEnv)
	mux.HandleFunc("GET /api/connect/env/{service}", a.connectEnv)
	mux.HandleFunc("GET /api/connect/files/{service}/{name}", a.connectFile)

	mux.HandleFunc("GET /api/clock", a.labClock)
	mux.HandleFunc("POST /api/clock", a.setLabClock)

	mux.HandleFunc("GET /api/config", a.getConfig)
	mux.HandleFunc("PUT /api/config/worldline-channel", a.putWorldlineChannel)

	mux.HandleFunc("POST /api/actions/worldline-cycle", a.runWorldlineCycle)
	mux.HandleFunc("POST /api/actions/settlement-pull", a.settlementPull)
	mux.HandleFunc("POST /api/actions/fund-sga", a.fundSGA)

	mux.HandleFunc("GET /api/plugins", a.listPlugins)
	mux.HandleFunc("POST /api/plugins", a.registerPlugin)
	mux.HandleFunc("DELETE /api/plugins/{id}", a.unregisterPlugin)
	mux.HandleFunc("POST /api/plugins/{id}/actions/{action}", a.pluginAction)
	mux.HandleFunc("GET /api/plugins/{id}/files", a.pluginFiles)
	mux.HandleFunc("POST /api/plugins/{id}/run", a.pluginRun)
	mux.HandleFunc("POST /api/plugins/{id}/files", a.pluginUpload)
	mux.HandleFunc("DELETE /api/plugins/{id}/files", a.pluginDeleteFile)
	mux.HandleFunc("GET /api/plugins/{id}/files/preview", a.pluginPreview)

	sub, err := fs.Sub(webFS, "web")
	if err != nil {
		log.Fatalf("console: embedded assets: %v", err)
	}
	// Embedded files carry no modification time, so a browser has nothing to
	// revalidate against and can keep last build's app.js after a rebuild.
	// no-cache makes it ask every time; the assets are a few hundred KB, local.
	static := http.FileServer(http.FS(sub))
	mux.Handle("GET /", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Cache-Control", "no-cache")
		static.ServeHTTP(w, r)
	}))
	// no-cache only reaches the next load. A tab left open across a rebuild
	// keeps running the page it loaded — buttons that post what an older
	// console posted — so every answer names the page this console serves,
	// and the page says so when it is no longer that one.
	build := webBuild(sub)
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("X-Console-Build", build)
		mux.ServeHTTP(w, r)
	})
}

// webBuild identifies the embedded page: a hash of every file under web/.
func webBuild(web fs.FS) string {
	h := sha256.New()
	_ = fs.WalkDir(web, ".", func(path string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		b, err := fs.ReadFile(web, path)
		if err != nil {
			return err
		}
		h.Write([]byte(path))
		h.Write(b)
		return nil
	})
	return hex.EncodeToString(h.Sum(nil))[:12]
}

// clientFor picks the HTTP client for a service. Banking Circle's
// real-shaped listener wants a client certificate; nothing else does.
func (a *app) clientFor(s console.Service) *http.Client {
	if len(s.BaseURL) > 5 && s.BaseURL[:5] == "https" {
		return a.secure
	}
	return a.client
}

func (a *app) baseURL(id string) string {
	s, ok := a.cat.Get(id)
	if !ok {
		return ""
	}
	return s.BaseURL
}

// tlsClient trusts caFile and presents the client certificate when both
// halves are present -- Banking Circle's API requires mTLS by default.
func tlsClient(caFile, certFile, keyFile string) (*http.Client, error) {
	pem, err := os.ReadFile(caFile)
	if err != nil {
		return nil, err
	}
	pool := x509.NewCertPool()
	if !pool.AppendCertsFromPEM(pem) {
		return nil, os.ErrInvalid
	}
	cfg := &tls.Config{RootCAs: pool, MinVersion: tls.VersionTLS12}
	if cert, err := tls.LoadX509KeyPair(certFile, keyFile); err == nil {
		cfg.Certificates = []tls.Certificate{cert}
	}
	return &http.Client{
		Timeout:   10 * time.Second,
		Transport: &http.Transport{TLSClientConfig: cfg},
	}, nil
}

func env(k, def string) string {
	if v := os.Getenv(k); v != "" {
		return v
	}
	return def
}

func envDuration(k string, def time.Duration) time.Duration {
	v := os.Getenv(k)
	if v == "" {
		return def
	}
	if d, err := time.ParseDuration(v); err == nil && d > 0 {
		return d
	}
	if n, err := strconv.Atoi(v); err == nil && n > 0 {
		return time.Duration(n) * time.Second
	}
	log.Printf("console: %s=%q is not a duration; using %s", k, v, def)
	return def
}

func logReq(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Static asset noise drowns out the calls that matter.
		if r.URL.Path != "/" && len(r.URL.Path) > 4 && r.URL.Path[:5] == "/api/" {
			log.Printf("%s %s", r.Method, r.URL.Path)
		}
		next.ServeHTTP(w, r)
	})
}
