# syntax=docker/dockerfile:1
FROM docker.io/library/golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod ./
COPY . .
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /out/payment-api ./cmd/paymentapi

FROM docker.io/library/alpine:3.20
RUN apk add --no-cache ca-certificates
COPY --from=build /out/payment-api /usr/local/bin/payment-api
USER 65532:65532
ENTRYPOINT ["/usr/local/bin/payment-api"]
